root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/hermes ."
bin = "./tmp/hermes"
include_ext = ["go", "env"]
exclude_dir = ["tmp", "bin"]
delay = 1000 # ms

[log]
time = true

[screen]
clear_on_rebuild = true 