# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  traefik:
    image: traefik:v3.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.cdn.address=:8081"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 8081
        target: 8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:alpine
    volumes:
      - uploads:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-domain.entrypoints=web"
      - "traefik.http.routers.nginx-domain.rule=Host(`cdn.viewtube.dev`) || Host(`cdn.docker.localhost`)"
      - "traefik.http.routers.nginx-ip.entrypoints=cdn"
      - "traefik.http.routers.nginx-ip.rule=HostRegexp(`{ip:^((\\d{1,3}\\.){3}\\d{1,3}|localhost)}`)"
      - "traefik.http.routers.nginx-ip.service=nginx"

  web:
    image: ghcr.io/viewtubeapp/web:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web-domain.entrypoints=web"
      - "traefik.http.routers.web-domain.rule=Host(`viewtube.dev`) || Host(`viewtube.docker.localhost`)"
      - "traefik.http.routers.web-ip.entrypoints=web"
      - "traefik.http.routers.web-ip.rule=HostRegexp(`{ip:^((\\d{1,3}\\.){3}\\d{1,3}|localhost)}`)"
      - "traefik.http.routers.web-ip.service=web"
    secrets:
      - db-password
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_DB=viewtube
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    env_file:
      - .envfile
    depends_on:
      - db
      - traefik
    volumes:
      - uploads:/app/public/uploads
    deploy:
      update_config:
        order: start-first

  db:
    image: postgres
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=viewtube
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  uploads:
  letsencrypt:

secrets:
  db-password:
    external: true
