services:
  traefik:
    image: traefik:v3.1
    command:
      # Global configuration
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"

      # API & Dashboard
      - "--api.insecure=true"
      - "--api.dashboard=true"

      # Entrypoints configuration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@${REMOTE_HOST}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 8080
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.middlewares.ip-whitelist.ipwhitelist.sourcerange=127.0.0.1/32"

  nginx:
    image: ghcr.io/viewtubeapp/nginx:${GIT_COMMIT_HASH:-latest}
    volumes:
      - uploads:/usr/share/nginx/html:ro
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"

      # Service configuration
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

      # Router configuration
      - "traefik.http.routers.nginx.rule=Host(`${CDN_HOST}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.priority=100"

      # Middleware
      - "traefik.http.routers.nginx.middlewares=nginx-ip-whitelist"
      - "traefik.http.middlewares.nginx-ip-whitelist.ipwhitelist.sourcerange=0.0.0.0/0"

      # TLS configuration
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"

  web:
    image: ghcr.io/viewtubeapp/web:${GIT_COMMIT_HASH:-latest}
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"

      # Service configuration
      - "traefik.http.services.web.loadbalancer.server.port=3000"

      # Router configuration
      - "traefik.http.routers.web.rule=Host(`${REMOTE_HOST}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.priority=100"

      # Middleware
      - "traefik.http.routers.web.middlewares=web-ip-whitelist"
      - "traefik.http.middlewares.web-ip-whitelist.ipwhitelist.sourcerange=0.0.0.0/0"

      # TLS configuration
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
    secrets:
      - db-password
    depends_on:
      - db
      - traefik
      - nginx
      - redis
      - hermes
    volumes:
      - uploads:/app/public/uploads
    deploy:
      update_config:
        order: start-first

  db:
    image: postgres
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${CODENAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  hermes:
    image: ghcr.io/viewtubeapp/hermes:${GIT_COMMIT_HASH:-latest}
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:
  uploads:
  letsencrypt:

secrets:
  db-password:
    external: true
