version: "3.8"

include:
  - .docker/compose/app.yaml
  - .docker/compose/database.yaml
  - .docker/compose/monitoring.yaml
  - .docker/compose/tools.yaml

volumes:
  letsencrypt:
  grafana-data:
  portainer-data:
  prometheus-data:

secrets:
  grafana-password:
    external: true
  traefik-password:
    external: true
  prometheus-password:
    external: true

networks:
  default:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"
