FROM rabbitmq:3-management

COPY rabbitmq.conf /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf

EXPOSE 5672 15672 15692

ENV RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
ENV RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

CMD ["rabbitmq-server"]