FROM rabbitmq:3-management

COPY rabbitmq.conf /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf

# Add script to read password from file
COPY <<EOF /docker-entrypoint.d/10-set-password.sh
#!/bin/sh
if [ -f /run/secrets/rabbitmq-password ]; then
    export RABBITMQ_PASSWORD=$(cat /run/secrets/rabbitmq-password)
fi
EOF

RUN chmod +x /docker-entrypoint.d/10-set-password.sh

EXPOSE 5672 15672 15692

CMD ["rabbitmq-server"]