FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY extra/hermes/go.mod extra/hermes/go.sum ./
RUN go mod download

COPY extra/hermes/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /hermes

FROM alpine:3.21

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY --from=builder /hermes .

CMD ["./hermes"]
