FROM imbios/bun-node:1.2.4-22.14.0-alpine AS base

RUN apk add --no-cache --update ffmpeg

WORKDIR /usr/src/app

FROM base AS build

ENV SKIP_ENV_VALIDATION=true

ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_BRAND
ARG NEXT_PUBLIC_CDN_URL
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_GIT_COMMIT_HASH
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

COPY package.json .
COPY bun.lock .

RUN bun install

COPY . .

RUN bun run build

FROM base AS serve

WORKDIR /app

COPY --from=build /usr/src/app/package.json .
COPY --from=build /usr/src/app/bun.lock .
RUN bun install --production

COPY --from=build /usr/src/app/src ./src
COPY --from=build /usr/src/app/.next ./.next
COPY --from=build /usr/src/app/tsconfig.json .
COPY --from=build /usr/src/app/public ./public
COPY --from=build /usr/src/app/next.config.ts .
COPY --from=build /usr/src/app/drizzle.config.ts .
COPY --from=build /usr/src/app/messages ./.messages

EXPOSE 3000

CMD ["/bin/sh", "-c", "bun run db:push --force && bun run start"]
